// Pure helpers that turn a gathered schema model into a Markdown document.
import type { ForeignKeyDef, IndexDef } from '@shared/types'
import { fmtBytes } from './perf'

export interface DocColumn {
  name: string
  type: string
  nullable: boolean
  default: string | null
  isPrimaryKey: boolean
  /** `refTable.refColumn` if this column is a foreign key. */
  fk?: string
}

export interface DocTable {
  name: string
  schema?: string
  columns: DocColumn[]
  foreignKeys: ForeignKeyDef[]
  indexes: IndexDef[]
  rows: number | null
  bytes: number | null
  /** Optional AI-written one-line summary of the table's purpose. */
  description?: string
}

export interface DocModel {
  connName: string
  driver: string
  generatedAt: string
  tables: DocTable[]
  totalBytes: number
}

/** GitHub-style heading slug for in-document anchor links. */
export function slug(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
}

function esc(s: string): string {
  return s.replace(/\|/g, '\\|')
}

export function buildMarkdown(m: DocModel): string {
  const out: string[] = []
  out.push(`# ${m.connName} — Database Documentation`)
  out.push('')
  out.push(`_Generated by DataDock on ${new Date(m.generatedAt).toLocaleString()}_`)
  out.push('')
  const sizeNote = m.totalBytes ? ` · **Total size:** ${fmtBytes(m.totalBytes)}` : ''
  out.push(`**Engine:** ${m.driver} · **Tables:** ${m.tables.length}${sizeNote}`)
  out.push('')

  // Table of contents
  out.push('## Contents')
  out.push('')
  for (const t of m.tables) {
    const meta = t.rows != null ? ` — ${t.rows.toLocaleString()} rows` : ''
    out.push(`- [${t.name}](#${slug(t.name)})${meta}`)
  }
  out.push('')

  for (const t of m.tables) {
    out.push('---')
    out.push('')
    out.push(`## ${t.name}`)
    out.push('')
    const bits: string[] = []
    if (t.rows != null) bits.push(`${t.rows.toLocaleString()} rows`)
    if (t.bytes != null) bits.push(fmtBytes(t.bytes))
    if (bits.length) {
      out.push(`_${bits.join(' · ')}_`)
      out.push('')
    }
    if (t.description) {
      out.push(t.description)
      out.push('')
    }

    // Columns
    out.push('| Column | Type | Null | Key | Default |')
    out.push('|---|---|:--:|:--:|---|')
    for (const c of t.columns) {
      const key = c.isPrimaryKey ? 'PK' : c.fk ? 'FK' : ''
      const def = c.default != null && c.default !== '' ? `\`${esc(c.default)}\`` : ''
      out.push(
        `| \`${esc(c.name)}\` | ${esc(c.type)} | ${c.nullable ? 'YES' : 'NO'} | ${key} | ${def} |`
      )
    }
    out.push('')

    // Foreign keys
    if (t.foreignKeys.length) {
      out.push('**Foreign keys**')
      out.push('')
      for (const fk of t.foreignKeys) {
        out.push(`- \`${esc(fk.column)}\` → \`${esc(fk.refTable)}.${esc(fk.refColumn)}\``)
      }
      out.push('')
    }

    // Indexes
    if (t.indexes.length) {
      out.push('**Indexes**')
      out.push('')
      for (const idx of t.indexes) {
        const u = idx.unique ? ' _(unique)_' : ''
        out.push(`- \`${esc(idx.name)}\` (${idx.columns.map((c) => `\`${esc(c)}\``).join(', ')})${u}`)
      }
      out.push('')
    }
  }

  return out.join('\n')
}
