// Turn a schema diff (from schemaDiff.ts) into dialect-aware migration DDL.
import { sqlDialect } from '@shared/types'
import type { SchemaColumn } from '@shared/types'
import type { TableDiff } from './schemaDiff'

function quote(driver: string, id: string): string {
  if (driver === 'mysql') return `\`${id}\``
  if (driver === 'mssql') return `[${id}]`
  return `"${id}"`
}

function addColumn(driver: string, table: string, c: SchemaColumn): string {
  const t = quote(driver, table)
  const col = quote(driver, c.name)
  const nn = c.nullable ? '' : ' NOT NULL'
  const kw = driver === 'mssql' ? 'ADD' : 'ADD COLUMN'
  return `ALTER TABLE ${t} ${kw} ${col} ${c.type}${nn};`
}

function dropColumn(driver: string, table: string, name: string): string {
  return `ALTER TABLE ${quote(driver, table)} DROP COLUMN ${quote(driver, name)};`
}

function changeColumn(
  driver: string,
  table: string,
  from: SchemaColumn,
  to: SchemaColumn
): string[] {
  const t = quote(driver, table)
  const col = quote(driver, to.name)
  const lines: string[] = []
  if (driver === 'postgres') {
    if (from.type !== to.type) lines.push(`ALTER TABLE ${t} ALTER COLUMN ${col} TYPE ${to.type};`)
    if (from.nullable !== to.nullable)
      lines.push(
        `ALTER TABLE ${t} ALTER COLUMN ${col} ${to.nullable ? 'DROP NOT NULL' : 'SET NOT NULL'};`
      )
  } else if (driver === 'mysql') {
    lines.push(`ALTER TABLE ${t} MODIFY COLUMN ${col} ${to.type}${to.nullable ? '' : ' NOT NULL'};`)
  } else if (driver === 'mssql') {
    lines.push(`ALTER TABLE ${t} ALTER COLUMN ${col} ${to.type}${to.nullable ? '' : ' NOT NULL'};`)
  } else {
    lines.push(
      `-- SQLite cannot ALTER ${table}.${to.name} (${from.type} → ${to.type}); recreate the table to change it.`
    )
  }
  return lines
}

function createTable(driver: string, table: string, cols: SchemaColumn[]): string {
  const pk = cols.filter((c) => c.isPrimaryKey).map((c) => quote(driver, c.name))
  const defs = cols.map((c) => `  ${quote(driver, c.name)} ${c.type}${c.nullable ? '' : ' NOT NULL'}`)
  if (pk.length) defs.push(`  PRIMARY KEY (${pk.join(', ')})`)
  return `CREATE TABLE ${quote(driver, table)} (\n${defs.join(',\n')}\n);`
}

function dropTable(driver: string, table: string): string {
  return `DROP TABLE ${quote(driver, table)};`
}

/**
 * Build a migration script from a diff.
 * @param toTarget true → make THIS connection match the target; false → reverse.
 */
export function buildMigration(diff: TableDiff[], driver: string, toTarget: boolean): string {
  driver = sqlDialect(driver)
  const out: string[] = []

  for (const t of diff) {
    if (t.status === 'same') continue

    if (t.status === 'onlyA') {
      // exists in "this" connection only
      if (toTarget) out.push(dropTable(driver, t.name))
      else out.push(createTable(driver, t.name, t.columns.map((c) => c.a!).filter(Boolean)))
      out.push('')
      continue
    }
    if (t.status === 'onlyB') {
      // exists in the target only
      if (toTarget) out.push(createTable(driver, t.name, t.columns.map((c) => c.b!).filter(Boolean)))
      else out.push(dropTable(driver, t.name))
      out.push('')
      continue
    }

    // changed table — per-column statements
    const stmts: string[] = []
    for (const c of t.columns) {
      if (c.status === 'same') continue
      if (c.status === 'added') {
        // present in target (b) but not here (a)
        if (toTarget) stmts.push(addColumn(driver, t.name, c.b!))
        else stmts.push(dropColumn(driver, t.name, c.name))
      } else if (c.status === 'removed') {
        // present here (a) but not in target (b)
        if (toTarget) stmts.push(dropColumn(driver, t.name, c.name))
        else stmts.push(addColumn(driver, t.name, c.a!))
      } else if (c.status === 'changed' && c.a && c.b) {
        const from = toTarget ? c.a : c.b
        const to = toTarget ? c.b : c.a
        stmts.push(...changeColumn(driver, t.name, from, to))
      }
    }
    if (stmts.length) {
      out.push(`-- ${t.name}`)
      out.push(...stmts, '')
    }
  }

  const body = out.join('\n').trim()
  if (!body) return '-- No structural differences — schemas already match.'

  return [
    '-- Migration generated by DataDock',
    `-- Direction: ${toTarget ? 'this connection → target' : 'target → this connection'}`,
    '-- Covers tables, columns, types, nullability and primary keys.',
    '-- Does NOT include defaults, foreign keys, indexes or data — review before running.',
    '',
    body
  ].join('\n')
}
